[Launch]
Help_URL = http://121.40.240.143:9999/08504html.html

# 游戏运行Exe
GameExe = Bin\Game.exe

#更新文件URL
PatchInfo = http://121.40.240.143:9999/wxsj/patchinfo.txt

#游戏服务器信息文件
LoginServer = http://121.40.240.143:9999/wxsj/LoginServer.txt

#新版Launch的下载地址
NewLauncher = http://update.tl.sohu.com/tlbb/newlaunch.zip

RepairServer = http://repair.tl.sohu.com/repair/

#备用下载服务器
RefrenceUpdateServer = update1.tl.sohu.com;update2.tl.sohu.com

RegURL = http://reg.tl.sohu.com/index.jsp
ChoiceURL = http://sde.game.sohu.com/payment/gamechoice.jsp
RegisterURL = http://repair.tl.sohu.com/reg/register.asp
DisableSoda = 0
