[System]
LoginID=2
DBIP=127.0.0.1
DBPort=3306
DBName=tlbbdb
DBUser=tlbbdb
DBPassword=123456
ClientVersion=1005
DBConnectCount=10
TurnPlayerCount=100
CryptPwd=0
ProxyConnect=1
;重复登录限制开关。启用同 IP 20 秒限制和内部登录次数计数。0 表示关闭。
ReLoginLimit=0
;异地 IP 登录保护开关。启用旧账号在线时的踢出/阻断逻辑。0 表示关闭。
ReLoginStop=0
;异地登录阻断时间，单位是毫秒。默认缺省值是 600000，即 10 分钟。
ReLoginStopTime=600000
;安全登录标记
NotifySafeSign=0
